# Generated by Django 2.2.6 on 2019-10-19 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('runners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('start_long', models.DecimalField(decimal_places=6, max_digits=10)),
                ('end_lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('end_long', models.DecimalField(decimal_places=6, max_digits=10)),
                ('finished', models.BooleanField(blank=True, default=False)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RteRunner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=7)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runmap.Route')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runners.Runner')),
            ],
        ),
    ]
