# Generated by Django 2.2.6 on 2019-11-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
