# Generated by Django 2.2.6 on 2019-11-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runmap', '0002_route_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='total_distance',
            field=models.DecimalField(decimal_places=2, default=6918, max_digits=8),
            preserve_default=False,
        ),
    ]
