# Generated by Django 2.2.3 on 2019-08-23 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbiters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitbiter',
            name='last_sync',
            field=models.DateField(default=datetime.date(2019, 8, 23)),
            preserve_default=False,
        ),
    ]
