# Generated by Django 2.0.3 on 2018-03-17 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbiters', '0002_auto_20180317_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitbiter',
            name='user',
        ),
    ]
