# Generated by Django 2.2.3 on 2019-08-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbiters', '0002_fitbiter_last_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbiter',
            name='last_sync',
            field=models.DateField(blank=True),
        ),
    ]
