# Generated by Django 2.2.3 on 2019-08-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbiters', '0003_auto_20190823_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbiter',
            name='last_sync',
            field=models.DateField(blank=True, null=True),
        ),
    ]
