# Generated by Django 2.0.3 on 2018-03-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbiters', '0003_remove_fitbiter_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbiter',
            name='fitbit_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
