# Generated by Django 2.2.3 on 2019-09-14 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbiters', '0004_auto_20190823_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitbiter',
            name='last_sync',
        ),
    ]
