# Generated by Django 2.2.6 on 2019-10-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('client_id', models.CharField(default='', max_length=10)),
                ('redirect_uri', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
