# Generated by Django 2.2.6 on 2019-10-19 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='redirect_uri',
        ),
    ]
