# Generated by Django 2.2.6 on 2019-10-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0002_remove_platform_redirect_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='redirect_uri',
            field=models.CharField(default='', max_length=100),
        ),
    ]
