# Generated by Django 2.2.6 on 2019-10-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0003_platform_redirect_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='client_secret',
            field=models.CharField(default='', max_length=50),
        ),
    ]
