# Generated by Django 2.2.3 on 2019-08-05 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fitbiters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitRunner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=7)),
                ('fitbiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fitbiters.Fitbiter')),
            ],
        ),
        migrations.CreateModel(
            name='FitRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('start_long', models.DecimalField(decimal_places=6, max_digits=10)),
                ('end_lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('end_long', models.DecimalField(decimal_places=6, max_digits=10)),
                ('fitrunners', models.ManyToManyField(to='fitmap.FitRunner')),
            ],
        ),
        migrations.CreateModel(
            name='FitMappedRte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('maprtedata', models.TextField()),
                ('order', models.PositiveSmallIntegerField()),
                ('fitroute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitmap.FitRoute')),
                ('fitrunner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitmap.FitRunner')),
            ],
        ),
    ]
