# Generated by Django 2.0.3 on 2018-03-31 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitMappedRte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fitroute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitmap.FitRoute')),
            ],
        ),
    ]
