# Generated by Django 2.2.3 on 2019-08-06 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitrunner',
            name='fitbiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitbiters.Fitbiter'),
        ),
    ]
