# Generated by Django 2.0.3 on 2018-03-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitmap', '0002_fitmappedrte'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitmappedrte',
            name='maprtedata',
            field=models.TextField(default='asdf'),
            preserve_default=False,
        ),
    ]
