# Generated by Django 2.2.3 on 2019-08-06 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitmap', '0002_auto_20190806_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitmappedrte',
            name='fitrunner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fitmap.FitRunner'),
        ),
    ]
