# Generated by Django 2.2.3 on 2019-08-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitmap', '0003_auto_20190806_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitroute',
            name='fitrunners',
        ),
        migrations.AddField(
            model_name='fitrunner',
            name='fitroute',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='fitmap.FitRoute'),
            preserve_default=False,
        ),
    ]
