# Generated by Django 2.0.3 on 2018-04-03 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitbiters', '0004_auto_20180318_2340'),
        ('fitmap', '0003_fitmappedrte_maprtedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitmappedrte',
            name='fitbiter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='fitbiters.Fitbiter'),
            preserve_default=False,
        ),
    ]
