# Generated by Django 2.2.3 on 2019-08-10 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitmap', '0004_auto_20190810_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitroute',
            name='last_update',
            field=models.DateField(default=datetime.date(2019, 8, 10)),
            preserve_default=False,
        ),
    ]
