# Generated by Django 2.0.3 on 2018-04-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitmap', '0004_fitmappedrte_fitbiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitmappedrte',
            name='colour',
            field=models.CharField(default='#000088', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fitmappedrte',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
