# Generated by Django 2.0.3 on 2018-04-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitmap', '0005_auto_20180409_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypoint',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
