# Generated by Django 2.2.3 on 2019-08-23 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitmap', '0006_auto_20190821_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitroute',
            old_name='last_update',
            new_name='start_date',
        ),
    ]
