# Generated by Django 2.2.3 on 2019-08-23 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitmap', '0007_auto_20190822_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitroute',
            name='start_date',
        ),
        migrations.AddField(
            model_name='fitrunner',
            name='last_update',
            field=models.DateField(default=datetime.date(2019, 8, 22)),
            preserve_default=False,
        ),
    ]
