# Generated by Django 2.2.3 on 2019-08-23 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitmap', '0008_auto_20190822_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitmappedrte',
            name='order',
        ),
    ]
