# Generated by Django 2.2.3 on 2019-08-24 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitmap', '0009_remove_fitmappedrte_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitrunner',
            name='last_update',
        ),
    ]
