# Generated by Django 2.2.6 on 2019-10-26 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stravaer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_id', models.CharField(max_length=15, unique=True)),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('runner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='runners.Runner')),
            ],
        ),
    ]
