# Generated by Django 2.2.6 on 2019-10-31 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runners', '0002_stravaer'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
