# Generated by Django 2.2.6 on 2019-11-02 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runners', '0003_runner_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='goal_set_date',
            field=models.DateField(default=datetime.date(2019, 11, 2)),
            preserve_default=False,
        ),
    ]
