# Generated by Django 2.2.6 on 2019-10-19 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runners', '0001_initial'),
        ('rundata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runners.Runner')),
            ],
            options={
                'verbose_name': 'Run Data',
                'verbose_name_plural': 'Run Data',
            },
        ),
        migrations.DeleteModel(
            name='FitData',
        ),
    ]
