# Generated by Django 2.2.6 on 2019-10-31 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundata', '0002_auto_20191019_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='rundata',
            name='goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rundata',
            name='goal_percent',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rundata',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
