# Generated by Django 2.2.6 on 2019-10-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundata', '0003_auto_20191031_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rundata',
            name='goal',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='rundata',
            name='goal_percent',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
    ]
