# Generated by Django 2.2.6 on 2019-10-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundata', '0004_auto_20191031_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rundata',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
