# Generated by Django 2.2.6 on 2019-10-31 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundata', '0005_auto_20191031_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rundata',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
