# Generated by Django 2.2.3 on 2019-07-26 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fitbiters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fitbiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitbiters.Fitbiter')),
            ],
            options={
                'verbose_name': 'Fitbit Data',
                'verbose_name_plural': 'Fitbit Data',
            },
        ),
    ]
