# Generated by Django 2.0.3 on 2018-03-18 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fitbiters', '0003_remove_fitbiter_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('steps', models.PositiveIntegerField()),
                ('fitbiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitbiters.Fitbiter')),
            ],
        ),
    ]
