# Generated by Django 2.0.3 on 2018-03-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitdata', '0002_auto_20180318_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitdata',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
